name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3
      
    - name: Compile .c file
      run: gcc huawei_bootloader_unlocker.c -o huawei_bootloader_unlocker
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: huawei_bootloader_unlocker
        path: ./huawei_bootloader_unlocker
      
